import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer';
import Header from '../components/Header'
import LargeCard from '../components/LargeCard';
import MediumCard from '../components/MediumCard';
import SmallCard from '../components/SmallCard';


export default function Home({exploreData , cardsData}) {
  return (
    <div>
      <Head>
        <title>airbnb - clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header   */}
      <Header />



      {/* Banner  */}
      <Banner />


      {/* main component ! from api ... */}
      <main className="max-w-7xl mx-auto px-8 sm:px-16"> 
        <section className="pt-6 shadow-xl">
          <h2 className="text-2xl font-bold pb-5 sm:text-3xl md:text-4xl">
            Explore Nearby

          </h2>
        <div className="grid grid-col-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {exploreData.map((item) => (
            <SmallCard img={item.img} key={item.img} distance={item.distance} location={item.location}/>
          ))}

        </div>
        </section>

        <section className="mt-6">
          <h2 className="text-2xl font-bold pb-5 sm:text-3xl md:text-4xl">Live Anywhere</h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {cardsData.map((item)=>(
              <MediumCard key={item.img} img={item.img} title={item.title}/>
            ))}
          </div>
        </section>
        <LargeCard img="https://links.papareact.com/4cj" title="The Greatest Outdoors" description="Wishlists curated by Airbnb"
        buttonText="Get Started"/>
      </main>

      <Footer />

    



     
     

    
    
    </div>
  )
}

export async function getStaticProps(){
  const exploreData = await fetch('https://links.papareact.com/pyp').then(
    (res) => res.json()
  );

  const cardsData = await fetch('https://links.papareact.com/zp1').then(
    (res) => (
      res.json()

    )
  );

  return {
    props:{
      exploreData,
      cardsData,
    }
  }
}
